// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_lah263.Models;

namespace Mission06_lah263.Migrations
{
    [DbContext(typeof(MovieApplicationContext))]
    [Migration("20230214055420_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06_lah263.Models.NewMovie", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            Category = "Action/Adventure",
                            Director = "Rod",
                            Edited = true,
                            Rating = "R",
                            Title = "The Accountant",
                            Year = 2016
                        },
                        new
                        {
                            MovieID = 2,
                            Category = "Comedy",
                            Director = "Jared Hess",
                            Edited = false,
                            Rating = "PG",
                            Title = "Nacho Libre",
                            Year = 2006
                        },
                        new
                        {
                            MovieID = 3,
                            Category = "Drama",
                            Director = "Andy Tennant",
                            Edited = false,
                            Rating = "PG",
                            Title = "Ever After",
                            Year = 1998
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
